-- ============================================================================
-- # Wind Energy — Step 01: Extensions and Configuration
-- ============================================================================
-- This part of the workshop models a globally distributed fleet of wind
-- turbines at FIXED coordinates. Each turbine reports wind speed and
-- direction; power output is then DERIVED from wind speed using the standard
-- turbine power equation rather than stored as a fake measurement.
--
-- That distinction is the teaching point. Raw sensor data is cheap to collect
-- and expensive to interpret. The value sits in the derived metric — and a
-- derived metric computed by an IMMUTABLE SQL function is reproducible,
-- testable, and usable inside continuous aggregates.
-- ============================================================================
-- ## Prerequisites
-- ============================================================================
-- 1. A TigerData Cloud service
--    https://console.cloud.timescale.com/signup
--
-- 2. Connection string from the TigerData Console:
--    postgres://tsdbadmin:<password>@<host>:<port>/tsdb?sslmode=require
--
-- 3. psql CLI installed (recommended):
--    https://www.tigerdata.com/blog/how-to-install-psql-on-mac-ubuntu-debian-windows
--
-- 4. Basic SQL knowledge
-- ============================================================================
-- ## What You'll Learn
-- ============================================================================
-- - PostGIS geography:     storing turbine locations for true metre-accurate distance
-- - Spatial indexing:      GiST indexes and why ST_DWithin beats ST_Distance
-- - Point-in-polygon:      assigning each turbine to a named region at seed time
-- - Derived metrics:       an IMMUTABLE power curve, not a lookup table
-- - Hypertables:           time-partitioned storage for the measurement stream
-- - Continuous aggregates: hourly, daily, and per-region rollups that self-refresh
-- - Columnstore + retention: automated data lifecycle for raw telemetry
-- ============================================================================


-- ============================================================================
-- ## Extensions
-- ============================================================================
-- timescaledb is pre-installed and pre-created on every Tiger Cloud service.
-- Verify rather than create, so this file is safe to re-run.

SELECT extname, extversion
  FROM pg_extension
 WHERE extname = 'timescaledb';

-- Expected: one row, e.g. timescaledb | 2.22.1
-- If you get zero rows you are not connected to a TigerData service.

-- PostGIS gives us geography/geometry types, spatial indexes, and the ~300
-- ST_* functions this workshop is built on.
CREATE EXTENSION IF NOT EXISTS postgis;

SELECT postgis_full_version();

-- Note the PostGIS version in that output. the Fleet Tracking workshop uses the geography overload
-- of ST_LineInterpolatePoint, which requires PostGIS 3.4 or newer; that file
-- carries a documented fallback if your service is older.


-- ============================================================================
-- ## A note on what is NOT enabled here
-- ============================================================================
-- The `http` extension (pgsql-http) would let us call a live weather API
-- directly from SQL — genuinely the nicest version of this workshop. It is not
-- available on Tiger Cloud, and neither is pg_net, so there is no way to make
-- an outbound HTTP request from inside the database.
--
-- Instead, step 06 builds a deterministic wind climatology model in PL/pgSQL.
-- That turns out to have real advantages for teaching: history is reproducible,
-- there is no API key or rate limit, and the workshop runs on a locked-down
-- conference network. The README documents how to swap in live Open-Meteo data
-- if you are running self-hosted with pgsql-http available.
--
-- pg_cron is likewise not used. It is listed for Tiger Cloud but requires
-- contacting support to enable, so it cannot be a workshop prerequisite.
-- You advance the simulation yourself by re-running 10_advance_simulation.sql.


-- ============================================================================
-- ## Workshop configuration
-- ============================================================================
-- SQL cannot read environment variables, and every row in this workshop is
-- generated by SQL. So the tunables live in a table that the generator
-- functions read. .env.example documents these but does not supply them.

CREATE TABLE IF NOT EXISTS workshop_config (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  description TEXT
);

INSERT INTO workshop_config (key, value, description) VALUES
  ('backfill_days',    '730', 'Wind Energy: days of history to generate (730 = 2 years, enough to show each region''s seasonal cycle twice)'),
  ('wind_step_minutes', '15', 'Wind Energy: interval between live wind measurements'),
  -- Storage lifecycle. Raw chunks older than this move to the columnstore, and
  -- the backfill writes DIRECTLY in columnar form for anything past it. Read by
  -- both 06 (generation) and 09 (policies) so the two cannot drift apart.
  ('columnstore_after_days', '7', 'Wind Energy: age at which raw chunks move to the columnstore'),
  ('cagg_columnstore_after_days', '30', 'Wind Energy: age at which aggregate chunks move to the columnstore (must exceed every refresh start_offset)'),
  -- Tiering to object storage is OPT-IN. It is billable, and chunks already
  -- uploaded are only brought back one at a time, so step 14 does nothing until
  -- this says 'true'. See 14_tiered_storage.sql.
  ('enable_tiering',    'false', 'Wind Energy: set true to apply the object-storage tiering policies in step 14'),
  -- Fleet shape, and the main lever on total data volume alongside
  -- backfill_days. Total turbines = num_plants x turbines_per_plant, and the
  -- telemetry is that times backfill_days times 1440/wind_step_minutes, in EACH
  -- of two hypertables.
  --
  -- The default is TWO PLANTS PER REGION (12 x 8 = 96 turbines), which at the
  -- 730-day default is ~6.8 million rows per hypertable and ~1 GB all in.
  --
  -- That volume used to be unreachable: the initial continuous-aggregate fill got
  -- OOM-killed partway through. It is fine now because step 08 fills the
  -- aggregates in monthly batches AND reconnects between them, which releases the
  -- memory that was accumulating across calls in one session. Read the note there
  -- before raising this much further — the fill is the binding constraint, not the
  -- backfill.
  -- Plants are handed out round-robin across the six regions, so num_plants = 6
  -- gives one plant per region, 12 gives two, and so on.
  ('num_plants',        '12', 'Wind Energy: wind plants to build (max 36, round-robin across 6 regions)'),
  ('turbines_per_plant', '8', 'Wind Energy: turbines per plant, laid out in a grid around the plant centre'),
  -- Turbine spacing, in ROTOR DIAMETERS. These are the real numbers wind
  -- developers use, and they exist entirely because of wake losses: a turbine
  -- sitting in another turbine's slipstream sees slower, more turbulent air.
  -- Crosswind neighbours can be packed closer than downwind ones.
  ('spacing_crosswind_rotors', '5', 'Wind Energy: turbine spacing across the prevailing wind, in rotor diameters'),
  ('spacing_downwind_rotors',  '8', 'Wind Energy: turbine spacing along the prevailing wind, in rotor diameters'),
  ('wake_decay_k',        '0.05', 'Wind Energy: Jensen wake decay constant (0.05 onshore, 0.04 offshore)'),
  -- Set to 'true' by reset_demo.sh when it is going to fill the aggregates with
  -- several parallel connections instead. Step 08's own serial fill then emits
  -- no statements, so the work happens exactly once either way. Left 'false' so
  -- that running the files by hand fills them, which is what you want when
  -- reading them.
  ('parallel_cagg_fill',  'false', 'Wind Energy: reset_demo.sh fills the aggregates in parallel; step 08 skips its serial fill')
-- DO NOTHING would keep a stale description from an older run, and the
-- description is load-bearing: reset_demo.sh --hard identifies this
-- workshop's keys by the 'Wind Energy: ' prefix. So refresh the description while
-- leaving VALUE alone — values are tunables the flags persist on purpose.
ON CONFLICT (key) DO UPDATE SET description = EXCLUDED.description;

-- Typed accessors, so the generators read configuration without repeating casts.
CREATE OR REPLACE FUNCTION cfg(p_key TEXT)
RETURNS TEXT
LANGUAGE sql STABLE AS $$
  SELECT value FROM workshop_config WHERE key = p_key;
$$;

CREATE OR REPLACE FUNCTION cfg_int(p_key TEXT)
RETURNS INTEGER
LANGUAGE sql STABLE AS $$
  SELECT value::INTEGER FROM workshop_config WHERE key = p_key;
$$;

CREATE OR REPLACE FUNCTION cfg_num(p_key TEXT)
RETURNS DOUBLE PRECISION
LANGUAGE sql STABLE AS $$
  SELECT value::DOUBLE PRECISION FROM workshop_config WHERE key = p_key;
$$;

-- Verify:
SELECT key, value, description FROM workshop_config ORDER BY key;

-- To reshape the fleet, change these and re-run steps 02 onwards:
--
--   UPDATE workshop_config SET value = '24' WHERE key = 'num_plants';
--   UPDATE workshop_config SET value = '12' WHERE key = 'turbines_per_plant';
--
-- The defaults build 12 plants x 8 turbines = 96 turbines, which at a 30-day
-- hourly backfill is about 69,000 rows per hypertable. Scale with care: the
-- generator also computes wake interactions between turbines inside each plant,
-- so cost grows with turbines_per_plant squared.

SELECT cfg_int('num_plants')                AS plants,
       cfg_int('turbines_per_plant')        AS turbines_each,
       cfg_int('num_plants') * cfg_int('turbines_per_plant') AS total_turbines,
       cfg_int('num_plants') * cfg_int('turbines_per_plant')
         * cfg_int('backfill_days')
         * (1440 / cfg_int('wind_step_minutes'))
                                            AS backfill_rows_per_hypertable;

--  plants | turbines_each | total_turbines | backfill_rows_per_hypertable
-- --------+---------------+----------------+------------------------------
--      12 |             8 |             96 |                        69120
-- (1 row)
